spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/hangsung
    username: root
    password: Rjsn937129!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 옵션은 필요에 따라 변경
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug